### ISSUE TITLE
Why the unsafe pointer reference?

### ISSUE THREAD

**Issue by coolaj86** [jxskiss/base62#1]
https://github.com/jxskiss/base62/blob/9b9fb350b5e3b720ebae75e762818b1010b85299/base62.go#L222

Wouldn't this be the same as `return string(bytes)` and `return []byte(str)`?

**Comment by jxskiss** [comment]
This is a common unsafe trick, it avoids unnecessary memory allocation.

**Comment by coolaj86** [comment]
Hmm... I didn't realize that sort of casting would reallocate. I always assumed it was Copy-on-Write.
